using System;
using System.Collections.Generic;

namespace REAccess.Mobile.Database.Models
{
    public partial class DdsSDataIndicatorRank
    {
        public int DistrictSk { get; set; }
        public string SnapshotPeriod { get; set; }
        public decimal? GdpRatio { get; set; }
        public decimal? GdpPerUnitAreaRatio { get; set; }
        public decimal? GdpPerCapitaPermenantResidentRatio { get; set; }
        public decimal? GdpYoyRatio { get; set; }
        public decimal? FixedAssetsInvestmentRatio { get; set; }
        public decimal? ImportAndExportRatio { get; set; }
        public decimal? ConsumerGoodsRetailSalesRatio { get; set; }
        public decimal? FisicalBudgetRevenueRatio { get; set; }
        public decimal? LocalGovernmentDebtPressureByGdpRatio { get; set; }
        public decimal? LandSizeRatio { get; set; }
        public decimal? PermenantResidentsRatio { get; set; }
        public decimal? NewPermenantResidentsRatio { get; set; }
        public decimal? PermenantResidentsYoyRatio { get; set; }
        public decimal? PermanentPopulationDensityRatio { get; set; }
        public decimal? RegisteredCompaniesRatio { get; set; }
        public decimal? RegisteredCompaniesYoyRatio { get; set; }
        public decimal? RegisteredBusinessDensityRatio { get; set; }
        public decimal? InternalTrafficConnectionRatio { get; set; }
        public decimal? ExternalTrafficConnectionRatio { get; set; }
        public decimal? HighLevelRailwayStationCountRatio { get; set; }
        public decimal? HighwayEntriesCountRatio { get; set; }
        public decimal? LogisticsStationCountRatio { get; set; }
        public decimal? LargeIndustrialEnterprisesCountRatio { get; set; }
        public decimal? LargeIndustrialCompanyCountYoyRatio { get; set; }
        public decimal? LargeCompanyTotalAssetRatio { get; set; }
        public decimal? LargeIndustrialCompanyTotalAssetRatioRatio { get; set; }
        public decimal? LargeIndustrialCompanyAverageAssetRatio { get; set; }
        public decimal? LargeIndustrialCompanyTotalProductionRatio { get; set; }
        public decimal? LargeIndustrialCompanyTotalProductionYoyRatio { get; set; }
        public decimal? LargeIndustrialCompanyAverageProductionRatio { get; set; }
        public decimal? LargeIndustrialCompanyProductionPerCapitaRatio { get; set; }
        public decimal? LargeIndustrialCompanyUnitAreaProductionRatio { get; set; }
        public decimal? ListedCompanyCountRatio { get; set; }
        public decimal? ListedRateRatio { get; set; }
        public decimal? ListedCompanyMarketValueRatio { get; set; }
        public decimal? ListedCompanyIncomeRatio { get; set; }
        public decimal? ListedCompanyIncomeYoyRatio { get; set; }
        public decimal? ListedCompanyEbitRatio { get; set; }
        public decimal? ListedCompanyEbitYoyRatio { get; set; }
        public decimal? InvestedCompaniesCountRatio { get; set; }
        public decimal? InvestedCompaniesCountYoyRatio { get; set; }
        public decimal? InvestedCompaniesCountRatioRatio { get; set; }
        public decimal? InvestedCompaniesInvestedAmountRatio { get; set; }
        public decimal? InvestedCompaniesInvestedAmountYoyRatio { get; set; }
        public decimal? InvestedCompaniesInvestedAmountRatioRatio { get; set; }
        public decimal? UnicornsCountRatio { get; set; }
        public decimal? UnicornsCountRatioRatio { get; set; }
        public decimal? UnicornsEstimatedValueRatio { get; set; }
        public decimal? UnicornsEstimatedValueRatioRatio { get; set; }
        public decimal? TechBasedSmeRatio { get; set; }
        public decimal? HighTechEnterprisesRatio { get; set; }
        public decimal? NationalPlatformsRatio { get; set; }
        public decimal? PostdoctoralResearchStationRatio { get; set; }
        public decimal? College211985Ratio { get; set; }
        public decimal? GraduatesAtSchoolCountRatio { get; set; }
        public decimal? UndergraduatesAtSchoolCountRatio { get; set; }
        public decimal? InventionPatentsPer10kPplRatio { get; set; }
        public decimal? ListedCompaniesResearchBudgetRatio { get; set; }
        public decimal? ListedCompaniesResearchInvestRatio { get; set; }
        public decimal? AverageIndustrialLandPriceRatio { get; set; }
        public decimal? AverageIndustrialRentRateRatio { get; set; }
        public decimal? AverageCommercialLandPriceRatio { get; set; }
        public decimal? AverageCommercialRentRateRatio { get; set; }
        public decimal? AverageCommercialLandAreaRatio { get; set; }
        public decimal? AverageIndustryCarrierCostRatio { get; set; }
        public decimal? RelativeLabourCostRatio { get; set; }
        public decimal? OrdinaryLabourCostRatio { get; set; }
        public decimal? IndustrialAverageCostRatio { get; set; }
        public decimal? RailwayStationCountRatioRatio { get; set; }
        public decimal? NumberOfBedsPerThousandRatio { get; set; }
        public decimal? HospitalCountRatio { get; set; }
        public decimal? NumberOfK12EducationSchoolsPer10kPplRatio { get; set; }
        public decimal? NumberOfInternationalSchoolsPer10kPplRatio { get; set; }
        public decimal? NumberOfHotelsPer10kPplRatio { get; set; }
        public decimal? NumberOfCinemasPer10kPplRatio { get; set; }
        public decimal? NumberOfSupermarketConvenienceStoresPer10kPplRatio { get; set; }
        public decimal? StarbucksPer10kPplRatio { get; set; }
        public decimal? NumberOfCultureFacilitiesPer10kPplRatio { get; set; }
        public decimal? ScenicSpotCountRatio { get; set; }
        public decimal? HousePriceIncomeRatioRatio { get; set; }
        public decimal? RentToIncomeRatioRatio { get; set; }
        public decimal? AirQualityRatio { get; set; }
        public decimal? CreditSupportsTheRealEconomyRatio { get; set; }
        public decimal? FinancialCompanyCountRatio { get; set; }
        public decimal? InvestmentCompanyCountRatio { get; set; }
        public decimal? FiscalSelfSupplimentRatio { get; set; }
        public decimal? RentToHousePriceRatioRatio { get; set; }
        public decimal? LabourOutputEfficiencyRatio { get; set; }
        public decimal? IndustryInvestmentCostEffectiveRatio { get; set; }
        public decimal? PopulationNetInflowRatio { get; set; }
        public decimal? UnitGdpElectricityConsumptionRatio { get; set; }
        public decimal? FisicalBudgetExpenditureRatio { get; set; }
        public decimal? DirectUseOfForeignCapitalRatio { get; set; }
        public decimal? DirectUseOfForeignCapitalYoyRatio { get; set; }
        public decimal? ResidentExpenditurePerCapitaRatio { get; set; }
        public decimal? NewEmploymentRatio { get; set; }
        public decimal? NewEmploymentRateRatio { get; set; }
        public decimal? LargeIndustrialCompanyValueAddedRatio { get; set; }
        public decimal? LargeIndustrialEnterprisesAssetsRatio { get; set; }
        public decimal? LargeEnterprisesStaffCountRatio { get; set; }
        public decimal? PrimaryIndustryValueAddedRatio { get; set; }
        public decimal? PrimaryIndustryValueAddedYoyRatio { get; set; }
        public decimal? SecondaryIndustryValueAddedRatio { get; set; }
        public decimal? SecondaryIndustryValueAddedYoyRatio { get; set; }
        public decimal? TertiaryIndustryValueAddedRatio { get; set; }
        public decimal? TertiaryIndustryValueAddedYoyRatio { get; set; }
        public decimal? IndustrialValueAddedRatio { get; set; }
        public decimal? IndustrialValueAddedYoyRatio { get; set; }
        public decimal? WholeSocietyElectricityConsumptionRatio { get; set; }
        public decimal? WholeSocietyElectricityConsumptionYoyRatio { get; set; }
        public decimal? IndustrialElectricityConsumptionRatio { get; set; }
        public decimal? UndergraduateAndAcademyRatio { get; set; }
        public decimal? DisposableIncomeRatio { get; set; }
        public decimal? NationalEnterpriseTechCentersRatio { get; set; }
        public decimal? NationalResearchLabsRatio { get; set; }
        public decimal? BondedLogisticsCenterBAmountRatio { get; set; }
        public decimal? SpecialCustomsControllingZoneAmountRatio { get; set; }
        public decimal? NationalAdvancedManufacturingIndustryAmountRatio { get; set; }
        public decimal? SolidSmallMediumEnterprisesAmountRatio { get; set; }
        public decimal? NationalTechBusinessIncubatorAmountRatio { get; set; }
        public decimal? NationalEcoDevelopmentZoneAmountRatio { get; set; }
        public decimal? NationalHighTechIndustrialDevelopmentZoneAmountRatio { get; set; }
        public decimal? ProvincialDevelopmentZoneAmountRatio { get; set; }
        public decimal? LocalGovernmentDebtRatio { get; set; }
        public decimal? BankLoanBalanceRatio { get; set; }
        public decimal? AirlineYearlyTakeoffLandingTimesRatio { get; set; }
        public decimal? TrainYearlyDepartTimesRatio { get; set; }
        public decimal? BusYearlyDepartTimesRatio { get; set; }
        public decimal? BankingFinancialInstitutionLegalEntityCountRatio { get; set; }
        public decimal? BankingFinancialInstitutionCountRatio { get; set; }
        public decimal? InsuranceInstitutionLegalEntityCountRatio { get; set; }
        public decimal? InsuranceInstitutionCountRatio { get; set; }
        public decimal? SecurityCompanyLegalEntityCountRatio { get; set; }
        public decimal? FuturesCompanyLegalEntityCountRatio { get; set; }
        public decimal? PublicFundInstitutionLegalEntityCountRatio { get; set; }
        public decimal? AvgRentRatio { get; set; }
        public decimal? UrbanResidentsDisposableIncomeRatio { get; set; }
        public decimal? UrbanResidentExpenditurePerCapitaRatio { get; set; }
        public decimal? HospitalBedsCountRatio { get; set; }
        public decimal? K12CountRatio { get; set; }
        public decimal? InternationSchoolCountRatio { get; set; }
        public decimal? RailwayStationCountRatio { get; set; }
        public decimal? SupermarketAndStoreCountRatio { get; set; }
        public decimal? HotelCountRatio { get; set; }
        public decimal? StarbucksCountRatio { get; set; }
        public decimal? CinemaCountRatio { get; set; }
        public decimal? CultureFacilitiesCountRatio { get; set; }
        public decimal? ScenicSpotCountPer100kPplRatio { get; set; }
        public decimal? AvgHousePriceRatio { get; set; }
    }
}
