using System;
using System.Collections.Generic;

namespace REAccess.Mobile.Database.Models
{
    public partial class DdsSDataIndicatorFixed
    {
        public int DistrictSk { get; set; }
        public string SnapshotPeriod { get; set; }
        public decimal? Gdp { get; set; }
        public decimal? GdpPerUnitArea { get; set; }
        public decimal? GdpPerCapitaPermenantResident { get; set; }
        public decimal? GdpYoy { get; set; }
        public decimal? FixedAssetsInvestment { get; set; }
        public decimal? ImportAndExport { get; set; }
        public decimal? ConsumerGoodsRetailSales { get; set; }
        public decimal? FisicalBudgetRevenue { get; set; }
        public decimal? LocalGovernmentDebtPressureByGdp { get; set; }
        public decimal? LandSize { get; set; }
        public decimal? PermenantResidents { get; set; }
        public decimal? NewPermenantResidents { get; set; }
        public decimal? PermenantResidentsYoy { get; set; }
        public decimal? PermanentPopulationDensity { get; set; }
        public decimal? RegisteredCompanies { get; set; }
        public decimal? RegisteredCompaniesYoy { get; set; }
        public decimal? RegisteredBusinessDensity { get; set; }
        public decimal? InternalTrafficConnection { get; set; }
        public decimal? ExternalTrafficConnection { get; set; }
        public decimal? HighLevelRailwayStationCount { get; set; }
        public decimal? HighwayEntriesCount { get; set; }
        public decimal? LogisticsStationCount { get; set; }
        public decimal? LargeIndustrialEnterprisesCount { get; set; }
        public decimal? LargeIndustrialCompanyCountYoy { get; set; }
        public decimal? LargeCompanyTotalAsset { get; set; }
        public decimal? LargeIndustrialCompanyTotalAssetRatio { get; set; }
        public decimal? LargeIndustrialCompanyAverageAsset { get; set; }
        public decimal? LargeIndustrialCompanyTotalProduction { get; set; }
        public decimal? LargeIndustrialCompanyTotalProductionYoy { get; set; }
        public decimal? LargeIndustrialCompanyAverageProduction { get; set; }
        public decimal? LargeIndustrialCompanyProductionPerCapita { get; set; }
        public decimal? LargeIndustrialCompanyUnitAreaProduction { get; set; }
        public decimal? ListedCompanyCount { get; set; }
        public decimal? ListedRate { get; set; }
        public decimal? ListedCompanyMarketValue { get; set; }
        public decimal? ListedCompanyIncome { get; set; }
        public decimal? ListedCompanyIncomeYoy { get; set; }
        public decimal? ListedCompanyEbit { get; set; }
        public decimal? ListedCompanyEbitYoy { get; set; }
        public decimal? InvestedCompaniesCount { get; set; }
        public decimal? InvestedCompaniesCountYoy { get; set; }
        public decimal? InvestedCompaniesCountRatio { get; set; }
        public decimal? InvestedCompaniesInvestedAmount { get; set; }
        public decimal? InvestedCompaniesInvestedAmountYoy { get; set; }
        public decimal? InvestedCompaniesInvestedAmountRatio { get; set; }
        public decimal? UnicornsCount { get; set; }
        public decimal? UnicornsCountRatio { get; set; }
        public decimal? UnicornsEstimatedValue { get; set; }
        public decimal? UnicornsEstimatedValueRatio { get; set; }
        public decimal? TechBasedSme { get; set; }
        public decimal? HighTechEnterprises { get; set; }
        public decimal? NationalPlatforms { get; set; }
        public decimal? PostdoctoralResearchStation { get; set; }
        public decimal? College211985 { get; set; }
        public decimal? GraduatesAtSchoolCount { get; set; }
        public decimal? UndergraduatesAtSchoolCount { get; set; }
        public decimal? InventionPatentsPer10kPpl { get; set; }
        public decimal? ListedCompaniesResearchBudget { get; set; }
        public decimal? ListedCompaniesResearchInvest { get; set; }
        public decimal? AverageIndustrialLandPrice { get; set; }
        public decimal? AverageIndustrialRentRate { get; set; }
        public decimal? AverageCommercialLandPrice { get; set; }
        public decimal? AverageCommercialRentRate { get; set; }
        public decimal? AverageCommercialLandArea { get; set; }
        public decimal? AverageIndustryCarrierCost { get; set; }
        public decimal? RelativeLabourCost { get; set; }
        public decimal? OrdinaryLabourCost { get; set; }
        public decimal? IndustrialAverageCost { get; set; }
        public decimal? RailwayStationCountRatio { get; set; }
        public decimal? NumberOfBedsPerThousand { get; set; }
        public decimal? HospitalCount { get; set; }
        public decimal? NumberOfK12EducationSchoolsPer10kPpl { get; set; }
        public decimal? NumberOfInternationalSchoolsPer10kPpl { get; set; }
        public decimal? NumberOfHotelsPer10kPpl { get; set; }
        public decimal? NumberOfCinemasPer10kPpl { get; set; }
        public decimal? NumberOfSupermarketConvenienceStoresPer10kPpl { get; set; }
        public decimal? StarbucksPer10kPpl { get; set; }
        public decimal? NumberOfCultureFacilitiesPer10kPpl { get; set; }
        public decimal? ScenicSpotCount { get; set; }
        public decimal? HousePriceIncomeRatio { get; set; }
        public decimal? RentToIncomeRatio { get; set; }
        public decimal? AirQuality { get; set; }
        public decimal? CreditSupportsTheRealEconomy { get; set; }
        public decimal? FinancialCompanyCount { get; set; }
        public decimal? InvestmentCompanyCount { get; set; }
        public decimal? FiscalSelfSuppliment { get; set; }
        public decimal? RentToHousePriceRatio { get; set; }
        public decimal? LabourOutputEfficiency { get; set; }
        public decimal? IndustryInvestmentCostEffective { get; set; }
        public decimal? PopulationNetInflow { get; set; }
        public decimal? UnitGdpElectricityConsumption { get; set; }
        public decimal? FisicalBudgetExpenditure { get; set; }
        public decimal? DirectUseOfForeignCapital { get; set; }
        public decimal? DirectUseOfForeignCapitalYoy { get; set; }
        public decimal? ResidentExpenditurePerCapita { get; set; }
        public decimal? NewEmployment { get; set; }
        public decimal? NewEmploymentRate { get; set; }
        public decimal? LargeIndustrialCompanyValueAdded { get; set; }
        public decimal? LargeIndustrialEnterprisesAssets { get; set; }
        public decimal? LargeEnterprisesStaffCount { get; set; }
        public decimal? PrimaryIndustryValueAdded { get; set; }
        public decimal? PrimaryIndustryValueAddedYoy { get; set; }
        public decimal? SecondaryIndustryValueAdded { get; set; }
        public decimal? SecondaryIndustryValueAddedYoy { get; set; }
        public decimal? TertiaryIndustryValueAdded { get; set; }
        public decimal? TertiaryIndustryValueAddedYoy { get; set; }
        public decimal? IndustrialValueAdded { get; set; }
        public decimal? IndustrialValueAddedYoy { get; set; }
        public decimal? WholeSocietyElectricityConsumption { get; set; }
        public decimal? WholeSocietyElectricityConsumptionYoy { get; set; }
        public decimal? IndustrialElectricityConsumption { get; set; }
        public decimal? UndergraduateAndAcademy { get; set; }
        public decimal? DisposableIncome { get; set; }
        public decimal? NationalResearchLabs { get; set; }
        public decimal? NationalEnterpriseTechCenters { get; set; }
        public decimal? AvgHousePrice { get; set; }
        public decimal? OrdinaryLabourMonthlyCost { get; set; }
        public decimal? BondedLogisticsCenterBAmount { get; set; }
        public decimal? SpecialCustomsControllingZoneAmount { get; set; }
        public decimal? NationalAdvancedManufacturingIndustryAmount { get; set; }
        public decimal? SolidSmallMediumEnterprisesAmount { get; set; }
        public decimal? NationalTechBusinessIncubatorAmount { get; set; }
        public decimal? NationalEcoDevelopmentZoneAmount { get; set; }
        public decimal? NationalHighTechIndustrialDevelopmentZoneAmount { get; set; }
        public decimal? ProvincialDevelopmentZoneAmount { get; set; }
        public decimal? LocalGovernmentDebt { get; set; }
        public decimal? BankLoanBalance { get; set; }
        public decimal? AirlineYearlyTakeoffLandingTimes { get; set; }
        public decimal? TrainYearlyDepartTimes { get; set; }
        public decimal? BusYearlyDepartTimes { get; set; }
        public decimal? BankingFinancialInstitutionLegalEntityCount { get; set; }
        public decimal? BankingFinancialInstitutionCount { get; set; }
        public decimal? InsuranceInstitutionLegalEntityCount { get; set; }
        public decimal? InsuranceInstitutionCount { get; set; }
        public decimal? SecurityCompanyLegalEntityCount { get; set; }
        public decimal? FuturesCompanyLegalEntityCount { get; set; }
        public decimal? PublicFundInstitutionLegalEntityCount { get; set; }
        public decimal? AvgRent { get; set; }
        public decimal? UrbanResidentsDisposableIncome { get; set; }
        public decimal? UrbanResidentExpenditurePerCapita { get; set; }
        public decimal? HospitalBedsCount { get; set; }
        public decimal? K12Count { get; set; }
        public decimal? InternationSchoolCount { get; set; }
        public decimal? RailwayStationCount { get; set; }
        public decimal? SupermarketAndStoreCount { get; set; }
        public decimal? HotelCount { get; set; }
        public decimal? StarbucksCount { get; set; }
        public decimal? CinemaCount { get; set; }
        public decimal? CultureFacilitiesCount { get; set; }
        public decimal? ScenicSpotCountPer100kPpl { get; set; }
    }
}
